INSERT INTO Author (name, age) VALUES ('Author 1', 34);
INSERT INTO Author (name, age) VALUES ('Author 2', 29);
INSERT INTO Author (name, age) VALUES ('Author 3', 41);
INSERT INTO Author (name, age) VALUES ('Author 4', 37);
INSERT INTO Author (name, age) VALUES ('Author 5', 45);
INSERT INTO Author (name, age) VALUES ('Author 6', 30);
INSERT INTO Author (name, age) VALUES ('Author 7', 50);
INSERT INTO Author (name, age) VALUES ('Author 8', 28);
INSERT INTO Author (name, age) VALUES ('Author 9', 32);
INSERT INTO Author (name, age) VALUES ('Author 10', 39);

INSERT INTO Article (name, date_publication, author_id) VALUES ('Article 1A', '2023-01-15', 1);
INSERT INTO Article (name, date_publication, author_id) VALUES ('Article 1B', '2023-02-20', 1);
INSERT INTO Article (name, date_publication, author_id) VALUES ('Article 2A', '2023-03-12', 2);
INSERT INTO Article (name, date_publication, author_id) VALUES ('Article 3A', '2023-04-05', 3);
INSERT INTO Article (name, date_publication, author_id) VALUES ('Article 3B', '2023-05-10', 3);
INSERT INTO Article (name, date_publication, author_id) VALUES ('Article 3C', '2023-06-15', 3);
INSERT INTO Article (name, date_publication, author_id) VALUES ('Article 4A', '2023-07-22', 4);
INSERT INTO Article (name, date_publication, author_id) VALUES ('Article 4B', '2023-08-01', 4);
INSERT INTO Article (name, date_publication, author_id) VALUES ('Article 5A', '2023-09-14', 5);
INSERT INTO Article (name, date_publication, author_id) VALUES ('Article 6A', '2023-10-02', 6);
INSERT INTO Article (name, date_publication, author_id) VALUES ('Article 6B', '2023-11-07', 6);
INSERT INTO Article (name, date_publication, author_id) VALUES ('Article 7A', '2023-12-10', 7);
INSERT INTO Article (name, date_publication, author_id) VALUES ('Article 8A', '2024-01-20', 8);
INSERT INTO Article (name, date_publication, author_id) VALUES ('Article 8B', '2024-02-25', 8);
INSERT INTO Article (name, date_publication, author_id) VALUES ('Article 9A', '2024-03-15', 9);
INSERT INTO Article (name, date_publication, author_id) VALUES ('Article 10A', '2024-04-05', 10);
INSERT INTO Article (name, date_publication, author_id) VALUES ('Article 10B', '2024-05-12', 10);
INSERT INTO Article (name, date_publication, author_id) VALUES ('Article 10C', '2024-06-18', 10);
